# Backend Service Configuration (Create as Web Service)
backend:
  name: pms-backend
  type: web
  runtime: node
  buildCommand: cd database && npm install && cd ../server && npm install
  startCommand: cd server && npm start
  env:
    - NODE_ENV=production
    - PORT=5000
    - MONGODB_URI=mongodb+srv://admin:JXZWEMU6z4w1SvIJ@podmanagement.yv8dt9t.mongodb.net/podManagement?retryWrites=true&w=majority&appName=podManagement
    - ALLOWED_ORIGINS=https://pms-eqvv.onrender.com
    - DEBUG=false

# Frontend Service Configuration (Create as Static Site)
frontend:
  name: pms-frontend
  type: static
  rootDir: client
  buildCommand: npm install && npm run build
  publishDirectory: build
  env:
    - REACT_APP_API_URL=https://pms-backend-60nq.onrender.com
    - NODE_ENV=production
    - GENERATE_SOURCEMAP=false
