# Backend Service Configuration (Create as Web Service)
backend:
  name: pms-backend
  type: web
  runtime: node
  buildCommand: cd database && npm install && cd ../server && npm install
  startCommand: cd server && npm start
  env:
    - NODE_ENV=production
    - PORT=5000
    - MONGODB_URI=mongodb+srv://user:password@pointToYourDatabase
    - ALLOWED_ORIGINS=pathToFrontend
    - DEBUG=false

# Frontend Service Configuration (Create as Static Site)
frontend:
  name: pms-frontend
  type: static
  rootDir: client
  buildCommand: npm install && npm run build
  publishDirectory: build
  env:
    - REACT_APP_API_URL=pathToBackend
    - NODE_ENV=production
    - GENERATE_SOURCEMAP=false
